module Main

import System
import System.File

%default total

mdPath : String
mdPath = "/tmp/learn_idris_ch17_ex09.md"

pdfPath : String
pdfPath = "/tmp/learn_idris_ch17_ex09.pdf"

covering
main : IO ()
main = do
  Right () <- writeFile mdPath "# Hello pandoc\n\nThis was generated by Idris.\n"
    | Left err => putStrLn ("error: " ++ show err)
  code <- System.system ("pandoc " ++ mdPath ++ " -o " ++ pdfPath)
  printLn code
