module ContentBuild.Emit

import Data.List
import Data.List1
import Data.String
import System.File
import ContentBuild.Scan

%default total

------------------------------------------------------------------------
-- Slug -> PascalCase ctor name.
-- "ch00-hello" -> "Ch00Hello"
-- "ch13-web-scraping" -> "Ch13WebScraping"
------------------------------------------------------------------------

capitalize : String -> String
capitalize s = case unpack s of
  []        => ""
  (c :: cs) => pack (toUpper c :: cs)

ctorOf : (slug : String) -> String
ctorOf slug =
  fastConcat (map capitalize (toList (split (== '-') slug)))

------------------------------------------------------------------------
-- String escaping for Idris source. Doubles backslashes + escapes ".
------------------------------------------------------------------------

escape : String -> String
escape s = pack (concatMap esc (unpack s))
  where
    esc : Char -> List Char
    esc '\\' = ['\\', '\\']
    esc '"'  = ['\\', '"']
    esc c    = [c]

------------------------------------------------------------------------
-- Emit lines for the data Route declaration.
------------------------------------------------------------------------

dataDecl : List Chapter -> String
dataDecl chs =
  let names = map (ctorOf . slug) chs
   in case names of
        []       => "data Route = Nil"
        [n]      => "data Route = " ++ n
        (n :: ns) =>
          "data Route\n  = " ++ n ++
          fastConcat (map (\m => "\n  | " ++ m) ns)

------------------------------------------------------------------------
-- Render one row of the lessonMeta function.
------------------------------------------------------------------------

metaRow : Chapter -> String
metaRow ch =
  "lessonMeta " ++ ctorOf ch.slug ++
  " = MkLessonMeta " ++ show ch.chapterNum ++
  " (MkLessonSlug \"" ++ escape ch.slug ++ "\")" ++
  " \"" ++ escape ch.title ++ "\"" ++
  " \"/assets/" ++ escape ch.slug ++ ".md\""

------------------------------------------------------------------------
-- Render one row of the toSlug function.
------------------------------------------------------------------------

toSlugRow : Chapter -> String
toSlugRow ch =
  "toSlug " ++ ctorOf ch.slug ++
  " = MkLessonSlug \"" ++ escape ch.slug ++ "\""

------------------------------------------------------------------------
-- Render one row of the fromSlug function.
------------------------------------------------------------------------

fromSlugRow : Chapter -> String
fromSlugRow ch =
  "fromSlug (MkLessonSlug \"" ++ escape ch.slug ++ "\") = Just " ++ ctorOf ch.slug

------------------------------------------------------------------------
-- Build the full file body.
------------------------------------------------------------------------

renderFile : List Chapter -> String
renderFile chs =
  let names      = map (ctorOf . slug) chs
      metaRows   = map metaRow    chs
      toRows     = map toSlugRow  chs
      fromRows   = map fromSlugRow chs
      allList    = "[" ++ joinBy ", " names ++ "]"
   in joinBy "\n"
      [ "module Generated.Routes"
      , ""
      , "import JSON.Derive"
      , "import Shared.Ids"
      , ""
      , "%default total"
      , "%language ElabReflection"
      , ""
      , "-- AUTO-GENERATED by web/content-build. Do not edit by hand."
      , "-- Re-run `make web-content` after editing chapter READMEs."
      , ""
      , "public export"
      , dataDecl chs
      , ""
      , "public export"
      , "record LessonMeta where"
      , "  constructor MkLessonMeta"
      , "  chapter   : Nat"
      , "  slug      : LessonSlug"
      , "  title     : String"
      , "  assetPath : String"
      , ""
      , "%runElab derive \"Route\"      [Show, Eq, Ord, ToJSON, FromJSON]"
      , "%runElab derive \"LessonMeta\" [Show, Eq, ToJSON, FromJSON]"
      , ""
      , "public export"
      , "lessonMeta : Route -> LessonMeta"
      , joinBy "\n" metaRows
      , ""
      , "public export"
      , "allRoutes : List Route"
      , "allRoutes = " ++ allList
      , ""
      , "public export"
      , "toSlug : Route -> LessonSlug"
      , joinBy "\n" toRows
      , ""
      , "public export"
      , "fromSlug : LessonSlug -> Maybe Route"
      , joinBy "\n" fromRows
      , "fromSlug _ = Nothing"
      , ""
      ]

------------------------------------------------------------------------
-- Write the rendered Routes.idr to disk.
------------------------------------------------------------------------

export covering
writeRoutesModule : (outPath : String) -> List Chapter -> IO ()
writeRoutesModule outPath chs = do
  Right () <- writeFile outPath (renderFile chs)
    | Left err => putStrLn ("ERROR writing " ++ outPath ++ ": " ++ show err)
  putStrLn ("wrote " ++ outPath ++ " (" ++ show (length chs) ++ " routes)")
